version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://parking_user:postgres@db:5432/parking_db
    volumes:
      - .:/app

volumes:
  db_data: